In [58]:
html_part ="""
<!DOCTYPE html>
<meta charset="utf-8">

<!-- Load d3.js -->
<script src="https://d3js.org/d3.v4.js"></script>

<!-- Create a div where the graph will take place -->
<div id="my_dataviz"></div>

<script>

// set the dimensions and margins of the graph
var margin = {top: 10, right: 30, bottom: 20, left: 50},
    width = 460 - margin.left - margin.right,
    height = 400 - margin.top - margin.bottom;

// append the svg object to the body of the page
var svg = d3.select("#my_dataviz")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform",
          "translate(" + margin.left + "," + margin.top + ")");

  var data = |jsondata|

  // List of subgroups = header of the csv files = soil condition here
  var subgroups = |groups|

  // List of groups = species here = value of the first column called group -> I show them on the X axis
  var groups = d3.map(data, function(d){return(d.|group|)}).keys()

  // Add X axis
  var x = d3.scaleBand()
      .domain(groups)
      .range([0, width])
      .padding([0.2])
  svg.append("g")
    .attr("transform", "translate(0," + height + ")")
    .call(d3.axisBottom(x).tickSize(0));

  // Add Y axis
  var y = d3.scaleLinear()
    .domain([0, 40])
    .range([ height, 0 ]);
  svg.append("g")
    .call(d3.axisLeft(y));

  // Another scale for subgroup position?
  var xSubgroup = d3.scaleBand()
    .domain(subgroups)
    .range([0, x.bandwidth()])
    .padding([0.05])

  // color palette = one color per subgroup
  var color = d3.scaleOrdinal()
    .domain(subgroups)
    .range(['#e41a1c','#377eb8','#4daf4a'])

  // Show the bars
  svg.append("g")
    .selectAll("g")
    // Enter in data = loop group per group
    .data(data)
    .enter()
    .append("g")
      .attr("transform", function(d) { return "translate(" + x(d.|group|) + ",0)"; })
    .selectAll("rect")
    .data(function(d) { return subgroups.map(function(key) { return {key: key, value: d[key]}; }); })
    .enter().append("rect")
      .attr("x", function(d) { return xSubgroup(d.key); })
      .attr("y", function(d) { return y(d.value); })
      .attr("width", xSubgroup.bandwidth())
      .attr("height", function(d) { return height - y(d.value); })
      .attr("fill", function(d) { return color(d.key); });


</script>

"""

In [59]:
import pandas as pd

dict_df = {"group":["banana","apple","sorgho","triticum"],"Nitrogen":[12,6,11,19],"normal":[1,6,28,6],"stress":[13,33,12,1]}
df = pd.DataFrame.from_dict(dict_df)

print(df.head())
print()

      group  Nitrogen  normal  stress
0    banana        12       1      13
1     apple         6       6      33
2    sorgho        11      28      12
3  triticum        19       6       1

In [60]:
new_df = {"sehir":["istanbul","ankara","izmir"],"nufus":[15,3,4],"kirlilik":[20,10,2]}
new_df = pd.DataFrame.from_dict(new_df)
new_df.head()

      sehir  nufus  kirlilik
0  istanbul     15        20
1    ankara      3        10
2     izmir      4         2

In [61]:
def constructchart(df, grouppart):

    df_json = df.to_json(orient="records")
    my_html = html_part.replace("|jsondata|", df_json)
    my_html = my_html.replace("|groups|", str(df.columns.tolist()[1:]))
    my_html = my_html.replace("|group|",grouppart)

#     print(my_html)
    my_file = open("deneme.html","w")
    my_file.write(my_html)
    my_file.close()
constructchart(new_df, "sehir")